version: '3'

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-node1-${CNTRL:-0}
    environment:
      - cluster.name=opensearch-cluster-${CNTRL:-0}
      - node.name=opensearch-node1-${CNTRL:-0}
      - discovery.type=single-node
      #- discovery.seed_hosts=opensearch-node1
      #- cluster.initial_master_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms${RAM_OSS:-1024m} -Xmx${RAM_OSS:-1024m}"
      - VIRTUAL_HOST=${VIRTUAL_HOST_OSS}
      - VIRTUAL_PORT=${VIRTUAL_PORT_OSS:-9200}
      - VIRTUAL_PROTO=${VIRTUAL_PROTO_OSS:-https}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-changeme@example.com}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_OSS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - ./config_instance-${CNTRL:-0}:/usr/share/opensearch/config
      - ./logs1-${CNTRL:-0}:/usr/share/opensearch/logs
      #### Only uncomment/change this when you know what you are doing
      #- ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - "${BIND_IP:-0.0.0.0}:${BIND_PORT_OSS:-9200}:9200"
      - "${BIND_IP:-0.0.0.0}:${BIND_PORT_OSA:-9600}:9600" # required for Performance Analyzer
    expose:
      - 9200
      - 9600
    networks:
      - opensearch-net
      - nginxproxy_net

    restart: unless-stopped

    depends_on:
      - fix-missing-files

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.6.0
    container_name: opensearch-dashboards-${CNTRL:-0}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_OSD}
      - VIRTUAL_PORT=${VIRTUAL_PORT_OSD:-5601}
      - VIRTUAL_PROTO=${VIRTUAL_PROTO_OSD:-http}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-changeme@example.com}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_OSD}
    ports:
      - ${BIND_IP:-0.0.0.0}:${BIND_PORT_ODS:-5601}:5601
    expose:
      - 5601
    volumes:
      - ./dev_opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
      - nginxproxy_net

    restart: unless-stopped
    
    depends_on:
      - opensearch-node1
    

  securityadmin:
    image: opensearchproject/opensearch:2.6.0
    container_name: securityadmin-${CNTRL:-0}
    volumes:
      - ./config_instance-${CNTRL:-0}:/usr/share/opensearch/config:ro
    command: >
      bash -c "sleep 60 && /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/opensearch/plugins/opensearch-security/securityconfig/ -icl -nhnv -cacert /usr/share/opensearch/config/root-ca.pem -cert /usr/share/opensearch/config/kirk.pem -key /usr/share/opensearch/config/kirk-key.pem -t internalusers -f /usr/share/opensearch/config/internal_users.yml"
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1

  fix-missing-files:
    image: opensearchproject/opensearch:2.6.0
    container_name: fix-missing-files-${CNTRL:-0}
    volumes:
      - ./config_instance-${CNTRL:-0}:/usr/share/opensearch/config
      - ./config_template:/config_template
      - ./internal_users.yml:/internal_users.yml
    command: >
      bash -c "cp -rn /config_template/* /usr/share/opensearch/config/ 2>/dev/null
      && [ -s "/internal_users.yml" ] && cp -f "/internal_users.yml" "/usr/share/opensearch/config/opensearch-security/internal_users.yml"
      && ([ -f /usr/share/opensearch/config/jvm.options ] || curl -o /usr/share/opensearch/config/jvm.options https://gist.githubusercontent.com/StiiCeva/c38b11b3dbe0b6917425d771fd938ec6/raw/f42c2d7b63a843e3f8204c8f304177876ce26170/jvm.options)
      && ([ -f /usr/share/opensearch/config/log4j2.properties ] || curl -o /usr/share/opensearch/config/log4j2.properties https://gist.githubusercontent.com/StiiCeva/a3138ee0dd3f42cede70c81a9bdc7309/raw/71dfcf0fe0f20b50ad29aa72d396b4d4e45e69d8/log4j2.properties)
      "

    networks:
      - opensearch-net

volumes:
  opensearch-data1:
    name: opensearch-data1-${CNTRL:-0}
  opensearch-config:

networks:
  opensearch-net:
    driver: bridge
    name: opensearch-net-${CNTRL:-0}
  nginxproxy_net:
    external: true