version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy-${VIRTUAL_HOST:-1}
    
    ports:
      - "${BIND_IP:-0.0.0.0}:${BIND_PORT:-9080}:80"
    
    environment:
      - TARGET_IP=${TARGET_IP:-10.243.1.200}
      - TARGET_PORT=${TARGET_PORT:-9200}
      - TARGET_PROTO=${TARGET_PROTO:-https}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT:-80}
      - VIRTUAL_PROTO=${VIRTUAL_PROTO:-https}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-changeme@example.com}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    command: /bin/bash -c "echo 'events {} http { server { listen 80; location / { proxy_pass $${TARGET_PROTO}://$${TARGET_IP}:$${TARGET_PORT}; proxy_http_version 1.1; proxy_set_header Connection \"Keep-Alive\"; proxy_set_header Proxy-Connection \"Keep-Alive\"; proxy_ssl_verify off; } } }' | envsubst > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

    expose:
      - "80"
      - "443"
    restart: unless-stopped
