version: '3'

services:
  letsencrypt:
    environment:
      LETSENCRYPT_EMAIL: the+letsencrypt@ciprianiacobescu.com
      NGINX_PROXY_CONTAINER: nsproxy
      DHPARAM_GENERATION: 'false'
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    volumes:
      - './certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - ngvh:/etc/nginx/vhost.d
      - nghtml:/usr/share/nginx/html
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    dns:
      - 1.1.1.1
      - 8.8.8.8

  nginx:
    image: 'jwilder/nginx-proxy:alpine'
    container_name: nsproxy
    environment:
      DHPARAM_GENERATION: 'false'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - './certs:/etc/nginx/certs:ro'
      - './client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro'
      - ngvh:/etc/nginx/vhost.d
      - nghtml:/usr/share/nginx/html
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    networks:
      - nginxproxy_net
    
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  nginxfolder:
  ngvh:
  nghtml:

networks:
  nginxproxy_net:
    external: true